AWSTemplateFormatVersion: "2010-09-09"
Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: "wide open group"
      SecurityGroupIngress:
      - IpProtocol: -1
        CidrIp: 0.0.0.0/0